import { INodeProperties } from "n8n-workflow";

const displayOptions = {
	show: {
		'/module': [
			'orders',
		],
	},
};

const addressFields: INodeProperties[] = [
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Company',
		name: 'company',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Street1',
		name: 'street1',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Street2',
		name: 'street2',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Street3',
		name: 'street3',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'City',
		name: 'city',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'State',
		name: 'state',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Postal Code',
		name: 'postalCode',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Country',
		name: 'country',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Phone',
		name: 'phone',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Residential',
		name: 'residential',
		type: 'boolean',
		default: '',
		displayOptions,
	},
];

const dimensionFields: INodeProperties[] = [
	{
		displayName: 'Units',
		name: 'units',
		type: 'string',
		default: '',
	},
	{
		displayName: 'Length',
		name: 'length',
		type: 'number',
		default: '',
	},
	{
		displayName: 'Width',
		name: 'width',
		type: 'number',
		default: '',
	},
	{
		displayName: 'Height',
		name: 'height',
		type: 'number',
		default: '',
	},
];

const weightFields: INodeProperties[] = [
	{
		displayName: 'Value',
		name: 'value',
		type: 'number',
		default: '',
	},
	{
		displayName: 'Units',
		name: 'units',
		type: 'options',
		default: '',
		options: [
			{
				name: 'Pounds',
				value: 'pounds',
			},
			{
				name: 'Ounces',
				value: 'ounces',
			},
			{
				name: 'Grams',
				value: 'grams',
			},
		],
	},
];

const orderItemFields: INodeProperties[] = [
	{
		displayName: 'Order Item Id',
		name: 'orderItemId',
		type: 'number',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Line Item Key',
		name: 'lineItemKey',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Sku',
		name: 'sku',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Image Url',
		name: 'imageUrl',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Weight',
		name: 'weight',
		type: 'collection',
		default: '',
		displayOptions,
		placeholder: 'Add weight data',
		options: weightFields,
	},
	{
		displayName: 'Quantity',
		name: 'quantity',
		type: 'number',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Unit Price',
		name: 'unitPrice',
		type: 'number',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Tax Amount',
		name: 'taxAmount',
		type: 'number',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Shipping Amount',
		name: 'shippingAmount',
		type: 'number',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Warehouse Location',
		name: 'warehouseLocation',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Product Id',
		name: 'productId',
		type: 'number',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Fulfillment Sku',
		name: 'fulfillmentSku',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Adjustment',
		name: 'adjustment',
		type: 'boolean',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Upc',
		name: 'upc',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Create Date',
		name: 'createDate',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Modify Date',
		name: 'modifyDate',
		type: 'string',
		default: '',
		displayOptions,
	},
];

const insuranceOptionsFields: INodeProperties[] = [
	{
		displayName: 'Provider',
		name: 'provider',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Insure Shipment',
		name: 'insureShipment',
		type: 'boolean',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Insured Value',
		name: 'insuredValue',
		type: 'number',
		default: '',
		displayOptions,
	},
];

const internationalOptionsFields: INodeProperties[] = [
	{
		displayName: 'Contents',
		name: 'contents',
		type: 'options',
		default: '',
		displayOptions,
		options: [
			{
				name: 'Merchandise',
				value: 'merchandise',
			},
			{
				name: 'Documents',
				value: 'documents',
			},
			{
				name: 'Gift',
				value: 'gift',
			},
			{
				name: 'Returned Goods',
				value: 'returned_goods',
			},
			{
				name: 'Sample',
				value: 'sample',
			},
		],
	},
	{
		displayName: 'Customs Items',
		name: 'customsItems',
		type: 'collection',
		default: '',
		typeOptions: {
			multipleValues: true,
		},
		displayOptions,
		options: [
			{
				displayName: 'Customs Item Id',
				name: 'customsItemId',
				type: 'string',
				default: '',
				displayOptions,
			},
			{
				displayName: 'description',
				name: 'description',
				type: 'string',
				default: '',
				displayOptions,
			},
			{
				displayName: 'Quantity',
				name: 'quantity',
				type: 'number',
				default: '',
				displayOptions,
			},
			{
				displayName: 'Value',
				name: 'value',
				type: 'number',
				default: '',
				displayOptions,
			},
			{
				displayName: 'Harmonized Tariff Code',
				name: 'harmonizedTariffCode',
				type: 'string',
				default: '',
				displayOptions,
			},
			{
				displayName: 'Country Of Origin',
				name: 'countryOfOrigin',
				type: 'string',
				default: '',
				displayOptions,
			},
		],
	},
	{
		displayName: 'Non Delivery',
		name: 'nonDelivery',
		type: 'options',
		default: 'return_to_sender',
		displayOptions,
		options: [
			{
				name: 'Return To Sender',
				value: 'return_to_sender',
			},
			{
				name: 'Treat As Abandoned',
				value: 'treat_as_abandoned',
			},
		],
	},
];

const advancedOptionsFields: INodeProperties[] = [
	{
		displayName: 'Warehouse Id',
		name: 'warehouseId',
		type: 'number',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Non Machinable',
		name: 'nonMachinable',
		type: 'boolean',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Saturday Delivery',
		name: 'saturdayDelivery',
		type: 'boolean',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Contains Alcohol',
		name: 'containsAlcohol',
		type: 'boolean',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Store Id',
		name: 'storeId',
		type: 'number',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Custom Field1',
		name: 'customField1',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Custom Field2',
		name: 'customField2',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Custom Field3',
		name: 'customField3',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Source',
		name: 'source',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Merged Or Split',
		name: 'mergedOrSplit',
		type: 'boolean',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Merged Ids',
		name: 'mergedIds',
		type: 'number',
		default: '',
		typeOptions: {
			multipleValues: true,
		},
		displayOptions,
	},
	{
		displayName: 'Parent Id',
		name: 'parentId',
		type: 'number',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Bill To Party',
		name: 'billToParty',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Bill To Account',
		name: 'billToAccount',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Bill To Postal Code',
		name: 'billToPostalCode',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Bill To Country Code',
		name: 'billToCountryCode',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Bill To My Other Account',
		name: 'billToMyOtherAccount',
		type: 'string',
		default: '',
		displayOptions,
	},
];

export const orderFields = [
	{
		displayName: 'Order Number',
		name: 'orderNumber',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Order Key',
		name: 'orderKey',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Order Date',
		name: 'orderDate',
		type: 'dateTime',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Payment Date',
		name: 'paymentDate',
		type: 'dateTime',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Ship By Date',
		name: 'shipByDate',
		type: 'dateTime',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Order Status',
		name: 'orderStatus',
		type: 'options',
		default: '',
		displayOptions,
		options: [
			{
				name: 'Awaiting Payment',
				value: 'awaiting_payment',
			},
			{
				name: 'Awaiting Shipment',
				value: 'awaiting_shipment',
			},
			{
				name: 'Shipped',
				value: 'shipped',
			},
			{
				name: 'On Hold',
				value: 'on_hold',
			},
			{
				name: 'Cancelled',
				value: 'cancelled',
			},
		],
	},
	{
		displayName: 'Customer Id',
		name: 'customerId',
		type: 'number',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Customer Username',
		name: 'customerUsername',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Customer Email',
		name: 'customerEmail',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Bill To',
		name: 'billTo',
		type: 'collection',
		default: '',
		displayOptions,
		placeholder: 'Select Address Field To Add',
		options: addressFields,
	},
	{
		displayName: 'Ship To',
		name: 'shipTo',
		type: 'collection',
		default: '',
		displayOptions,
		placeholder: 'Select Address Field To Add',
		options: addressFields,
	},
	{
		displayName: 'Items',
		name: 'items',
		type: 'collection',
		default: '',
		displayOptions,
		typeOptions: {
			multipleValues: true,
		},
		options: orderItemFields,
	},
	{
		displayName: 'Amount Paid',
		name: 'amountPaid',
		type: 'number',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Tax Amount',
		name: 'taxAmount',
		type: 'number',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Shipping Amount',
		name: 'shippingAmount',
		type: 'number',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Customer Notes',
		name: 'customerNotes',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Internal Notes',
		name: 'internalNotes',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Gift',
		name: 'gift',
		type: 'boolean',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Gift Message',
		name: 'giftMessage',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Payment Method',
		name: 'paymentMethod',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Requested Shipping Service',
		name: 'requestedShippingService',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Carrier Code',
		name: 'carrierCode',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Service Code',
		name: 'serviceCode',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Package Code',
		name: 'packageCode',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Confirmation',
		name: 'confirmation',
		type: 'string',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Ship Date',
		name: 'shipDate',
		type: 'dateTime',
		default: '',
		displayOptions,
	},
	{
		displayName: 'Weight',
		name: 'weight',
		type: 'collection',
		default: '',
		displayOptions,
		options: weightFields,
	},
	{
		displayName: 'Dimensions',
		name: 'dimensions',
		type: 'collection',
		default: '',
		displayOptions,
		options: dimensionFields,
	},
	{
		displayName: 'Insurance Options',
		name: 'insuranceOptions',
		type: 'collection',
		default: '',
		displayOptions,
		options: insuranceOptionsFields,
	},
	{
		displayName: 'International Options',
		name: 'internationalOptions',
		type: 'collection',
		default: '',
		displayOptions,
		options: internationalOptionsFields,
	},
	{
		displayName: 'Advanced Options',
		name: 'advancedOptions',
		type: 'collection',
		default: '',
		displayOptions,
		options: advancedOptionsFields,
	},
	{
		displayName: 'Tag Ids',
		name: 'tagIds',
		type: 'number',
		default: '',
		typeOptions: {
			multipleValues: true,
		},
		displayOptions,
	},
] as INodeProperties[];
